# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'game', '0001_initial'), (b'game', '0002_auto_20180416_0010'), (b'game', '0003_auto_20180416_0101'), (b'game', '0004_auto_20180416_0114'), (b'game', '0005_player_hand'), (b'game', '0006_auto_20180416_0140'), (b'game', '0007_auto_20180416_0146')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalSolution', models.ManyToManyField(to=b'game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('max_characters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.CreateModel(
            name='StartRoom',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.AddField(
            model_name='map',
            name='locations',
            field=models.ManyToManyField(to=b'game.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='adjacent_locations',
            field=models.ManyToManyField(through='game.AdjacentLocation', to=b'game.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='characters',
            field=models.ManyToManyField(to=b'game.Character'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Map'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to=b'game.Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='curr_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='adjacentlocation',
            name='original_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig', to='game.Location'),
        ),
        migrations.AddField(
            model_name='adjacentlocation',
            name='target_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game.Location'),
        ),
        migrations.RenameField(
            model_name='game',
            old_name='finalSolution',
            new_name='case_file',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(to=b'game.Card'),
        ),
        migrations.AddField(
            model_name='character',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(to=b'game.Character'),
        ),
    ]
