# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('card_type', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('case_file', models.ManyToManyField(to='game.Card')),
                ('characters', models.ManyToManyField(to='game.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('max_characters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_ready', models.BooleanField(default=False)),
                ('hand', models.ManyToManyField(to='game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.CreateModel(
            name='StartRoom',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Location')),
            ],
            bases=('game.location',),
        ),
        migrations.AddField(
            model_name='map',
            name='locations',
            field=models.ManyToManyField(to='game.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='adjacent_locations',
            field=models.ManyToManyField(through='game.AdjacentLocation', to='game.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='characters',
            field=models.ManyToManyField(to='game.Character'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Map'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='game.Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='curr_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='adjacentlocation',
            name='original_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig', to='game.Location'),
        ),
        migrations.AddField(
            model_name='adjacentlocation',
            name='target_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game.Location'),
        ),
    ]
