# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.ManyToManyField(to='game.Location')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='finalSolution',
            field=models.ManyToManyField(to='game.Card'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ManyToManyField(to='game.Map'),
        ),
    ]
