# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_active',
            new_name='game_state',
        ),
    ]
