# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180415_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
