# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180418_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(default=True),
        ),
    ]
