# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_turn_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_move',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='can_suggest',
            field=models.BooleanField(default=True),
        ),
    ]
