# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180420_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_game', to='game.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='case_file',
            field=models.ManyToManyField(related_name='case_file', to='game.Card'),
        ),
        migrations.CreateModel(
            name='Accusation',
            fields=[
                ('guess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Guess')),
            ],
            bases=('game.guess',),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('guess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Guess')),
            ],
            bases=('game.guess',),
        ),
        migrations.AddField(
            model_name='guess',
            name='crime_scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_scene', to='game.Card'),
        ),
        migrations.AddField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuse_game', to='game.Game'),
        ),
        migrations.AddField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuse_player', to='game.Player'),
        ),
        migrations.AddField(
            model_name='guess',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect', to='game.Card'),
        ),
        migrations.AddField(
            model_name='guess',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='game.Card'),
        ),
    ]
