# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180420_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(default=0),
        ),
    ]
