# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180421_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moved_by_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
