# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_moved_by_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_suggestion', to='game.Suggestion'),
        ),
    ]
