# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_active_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='refuting_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='game.Card'),
        ),
    ]
