# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_suggestion_refuting_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='refuting_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refuting_player', to='game.Player'),
        ),
    ]
